# Generated by Django 6.0.4 on 2026-04-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhealthrecord',
            name='sleep_architecture',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
