# Generated by Django 6.0.4 on 2026-04-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dailyhealthrecord_sleep_architecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhealthrecord',
            name='apnea_risk',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyhealthrecord',
            name='insomnia_risk',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyhealthrecord',
            name='pr_spikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyhealthrecord',
            name='sleep_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyhealthrecord',
            name='spo2_drops',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyhealthrecord',
            name='total_duration',
            field=models.IntegerField(default=480),
        ),
        migrations.AddField(
            model_name='dailyhealthrecord',
            name='total_movement',
            field=models.FloatField(default=0.0),
        ),
    ]
